blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

blog/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=70)

    body = models.TextField()

    created_time = models.DateTimeField()
    
    modified_time = models.DateTimeField()

    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category)

    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

blog/views.py
import markdown
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category

# Create your views here.

def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', context={
            'title': '小生的博客测试',
            'post_list': post_list,
            })

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
    return render(request, 'blog/detail.html', context={'post':post})

def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
    return render(request, 'blog/index.html', context={'post_list': post_list})

def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list=Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})

blog/templates/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html>
	<head>
		<title>xia0sheng的博客</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

        {% load staticfiles %}
	    <!-- css -->
		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="http://cdn.bootcss.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/friendly.css' %}">

	    <!-- js -->
	    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
	    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'blog/js/pace.min.js' %}"></script>
	    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body>
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="/"><b>xia0sheng的博客</b></a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="/" data-hover="Home">主页</a></li>
    								<li class="cl-effect-11"><a href="/" data-hover="Blog">博客</a></li>
    								<li class="cl-effect-11"><a href="/" data-hover="About">关于</a></li>
    								<li class="cl-effect-11"><a href="/" data-hover="Contact">联系我</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
		<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
                        {% block main %}
                        {% endblock main %}
					</main>
					<aside class="col-md-4">
						<div class="widget widget-recent-posts">		
							<h3 class="widget-title">最新文章</h3>		
                            {% get_recent_posts as recent_post_list %}
							<ul>
                                {% for post in recent_post_list %}
                                <li>
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }} </a>
                                </li>
                                {% endfor %}    
							</ul>
						</div>
						<div class="widget widget-archives">		
							<h3 class="widget-title">归档</h3>		
                            {% archives as date_list %}
							<ul>
                                {% for date in date_list %}
								<li>
									<a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
								</li>
                                {% endfor %}
							</ul>
						</div>

						<div class="widget widget-category">		
							<h3 class="widget-title">分类</h3>		
                            {% get_categories as category_list %}
							<ul>
                                {% for category in category_list %}
								<li>
									<a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
								</li>
                                {% endfor %}
							</ul>
						</div>
					</aside>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2017 <a href="http://blog.wangyouyu.com/" target="_blank" title="xia0sheng的博客">xia0sheng的博客</a></p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="/">主页</a></li>
					<li><a href="/">博客</a></li>
					<li><a href="/">关于</a></li>
					<li><a href="/">联系我</a></li>
				</ul>
			</nav>
		</div>

		<script src="{% static 'blog/js/script.js' %}"></script>

	</body>
</html>

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }} </a></span>
                <span class="post-date">
                    <a href="#">
                    <time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                    </a>
                </span>
                <span class="post-author"><a href="#">{{ post.author }} </a></span>
                <span class="comments-link"><a href="#">4 Comments</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area">
        <h2>留下你的评论</h2>
        <form action="#" method="post" class="comment-form">
            <div class="row">
                <div class="col-md-4">
                    <input type="text" name="name" placeholder="名字" required>
                </div>
                <div class="col-md-4">
                    <input type="email" name="email" placeholder="邮箱" required>
                </div>
                <div class="col-md-4">
                    <input type="text" name="url" placeholder="网址" required>
                </div>
                <div class="col-md-12">
                    <textarea name="comment" rows="7" placeholder="" required></textarea>
                    <button class=""><span>发表</span></button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list">
            <h2>评论列表</h2>
            <ul class="list-unstyled">
                <li class="comment-item">
                    <span class="name">追梦人物</span>
                    <time class="date">2017年3月12日 14:56</time>
                    <div class="text">
                        还不错哦
                    </div>
                </li>
                <li class="comment-item">
                    <span class="name">追梦人物</span>
                    <time class="date">2017年3月12日 14:56</time>
                    <div class="text">
                        还不错哦
                    </div>
                </li>
            </ul>
        </div>
    </section>
{% endblock main %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }} </a></span>
                    <span class="post-date">
                        <a href="#">
                            <time class="entry-date" datetime="{{ post.created_time }}">
                                {{ post.created_time }}
                            </time>
                        </a>
                    </span>
                    <span class="post-author"><a href="#">{{ post.author }} </a></span>
                    <span class="comments-link"><a href="#">4 Comments</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span
                            class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock main %}